import React from 'react';
import { Document, Page, Text, View, StyleSheet, Image } from '@react-pdf/renderer';
import type { ArchitecturePlan } from '../services/gemini';

const styles = StyleSheet.create({
  page: {
    flexDirection: 'column',
    backgroundColor: '#050505',
    color: '#ffffff',
    padding: 40,
    fontFamily: 'Helvetica',
  },
  titlePage: {
    flexDirection: 'column',
    backgroundColor: '#050505',
    color: '#ffffff',
    padding: 40,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 42,
    fontFamily: 'Times-Roman',
    marginBottom: 20,
    textAlign: 'center',
    textTransform: 'uppercase',
    letterSpacing: 2,
  },
  subtitle: {
    fontSize: 14,
    color: '#a1a1aa',
    textTransform: 'uppercase',
    letterSpacing: 4,
    marginBottom: 60,
  },
  heroImage: {
    width: '100%',
    height: 300,
    objectFit: 'cover',
    marginBottom: 40,
  },
  sectionTitle: {
    fontSize: 24,
    fontFamily: 'Times-Roman',
    marginBottom: 16,
    marginTop: 32,
    borderBottom: '1px solid #333',
    paddingBottom: 8,
    color: '#f4f4f5',
  },
  text: {
    fontSize: 11,
    lineHeight: 1.6,
    color: '#d4d4d8',
    marginBottom: 12,
  },
  listItem: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  bullet: {
    width: 10,
    fontSize: 11,
    color: '#d4d4d8',
  },
  itemContent: {
    flex: 1,
  },
  itemTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: '#ffffff',
    marginBottom: 4,
  },
  itemDesc: {
    fontSize: 11,
    lineHeight: 1.5,
    color: '#a1a1aa',
  },
  imageGrid: {
    flexDirection: 'column',
    justifyContent: 'flex-start',
    marginTop: 20,
  },
  imageContainer: {
    width: '100%',
    marginBottom: 30,
  },
  image: {
    width: '100%',
    height: 300,
    objectFit: 'cover',
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 9,
    color: '#52525b',
    flexDirection: 'row',
    justifyContent: 'space-between',
  }
});

interface PdfDocumentProps {
  plan: ArchitecturePlan;
  images: string[];
}

export const ArchitecturePdf = ({ plan, images }: PdfDocumentProps) => (
  <Document>
    {/* Title Page */}
    <Page size="A4" style={styles.titlePage}>
      <Text style={styles.subtitle}>Architectural Concept</Text>
      <Text style={styles.title}>{plan.title}</Text>
      {images[0] && <Image src={images[0]} style={styles.heroImage} />}
      <Text style={{ fontSize: 10, color: '#52525b', marginTop: 'auto' }}>
        Generated by ArchiGen AI Studio
      </Text>
    </Page>

    {/* Content Page 1 */}
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionTitle}>Concept Overview</Text>
      <Text style={styles.text}>{plan.conceptOverview}</Text>

      <Text style={styles.sectionTitle}>Design Principles</Text>
      {plan.designPrinciples.map((principle, i) => (
        <View key={i} style={styles.listItem}>
          <Text style={styles.bullet}>•</Text>
          <Text style={styles.text}>{principle}</Text>
        </View>
      ))}

      <Text style={styles.sectionTitle}>Material Palette</Text>
      {plan.materialPalette.map((mat, i) => (
        <View key={i} style={{ marginBottom: 12 }}>
          <Text style={styles.itemTitle}>{mat.name}</Text>
          <Text style={styles.itemDesc}>{mat.description}</Text>
        </View>
      ))}
      
      <View style={styles.footer} fixed>
        <Text>{plan.title}</Text>
        <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
      </View>
    </Page>

    {/* Content Page 2 */}
    <Page size="A4" style={styles.page}>
      <Text style={styles.sectionTitle}>Spatial Layout</Text>
      {plan.spatialLayout.map((space, i) => (
        <View key={i} style={{ marginBottom: 12 }}>
          <Text style={styles.itemTitle}>{space.area}</Text>
          <Text style={styles.itemDesc}>{space.description}</Text>
        </View>
      ))}

      {plan.dimensions && plan.dimensions.length > 0 && (
        <>
          <Text style={styles.sectionTitle}>Dimensions</Text>
          {plan.dimensions.map((dim, i) => (
            <View key={i} style={{ marginBottom: 8, flexDirection: 'row' }}>
              <Text style={{ ...styles.itemTitle, width: '40%' }}>{dim.area}</Text>
              <Text style={{ ...styles.itemDesc, width: '60%' }}>{dim.size}</Text>
            </View>
          ))}
        </>
      )}

      <Text style={styles.sectionTitle}>Construction Phases</Text>
      {plan.constructionPhases.map((phase, i) => (
        <View key={i} style={{ marginBottom: 12 }}>
          <Text style={styles.itemTitle}>Phase {i + 1}: {phase.phase}</Text>
          <Text style={styles.itemDesc}>{phase.details}</Text>
        </View>
      ))}
      
      <View style={styles.footer} fixed>
        <Text>{plan.title}</Text>
        <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
      </View>
    </Page>

    {/* Content Page 3 (Optional: Costing & Resources) */}
    {(plan.estimatedCost || plan.localResources || plan.executionStrategy) && (
      <Page size="A4" style={styles.page}>
        {plan.estimatedCost && plan.estimatedCost.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Estimated Costing</Text>
            {plan.estimatedCost.map((cost, i) => (
              <View key={i} style={{ marginBottom: 8, flexDirection: 'row' }}>
                <Text style={{ ...styles.itemTitle, width: '60%' }}>{cost.category}</Text>
                <Text style={{ ...styles.itemDesc, width: '40%' }}>{cost.cost}</Text>
              </View>
            ))}
            {plan.totalEstimatedCost && (
              <View style={{ marginTop: 12, paddingTop: 12, borderTop: '1px solid #333', flexDirection: 'row' }}>
                <Text style={{ ...styles.itemTitle, width: '60%' }}>Total Estimated Cost</Text>
                <Text style={{ ...styles.itemTitle, width: '40%' }}>{plan.totalEstimatedCost}</Text>
              </View>
            )}
          </>
        )}

        {plan.localResources && plan.localResources.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Local Resources</Text>
            {plan.localResources.map((resource, i) => (
              <View key={i} style={styles.listItem}>
                <Text style={styles.bullet}>•</Text>
                <Text style={styles.text}>{resource}</Text>
              </View>
            ))}
          </>
        )}

        {plan.executionStrategy && (
          <>
            <Text style={styles.sectionTitle}>Execution Strategy</Text>
            <Text style={styles.text}>{plan.executionStrategy}</Text>
          </>
        )}

        <View style={styles.footer} fixed>
          <Text>{plan.title}</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    )}

    {/* Renderings Page */}
    {images.length > 1 && (
      <Page size="A4" style={styles.page}>
        <Text style={styles.sectionTitle}>Architectural Renderings</Text>
        <View style={styles.imageGrid}>
          {images.slice(1).map((img, i) => (
            <View key={i} style={styles.imageContainer}>
              <Image src={img} style={styles.image} />
            </View>
          ))}
        </View>
        <View style={styles.footer} fixed>
          <Text>{plan.title}</Text>
          <Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} />
        </View>
      </Page>
    )}
  </Document>
);
